---

- hosts: all
  become: true
  tasks:


  - name: install apache2 pakage and php for Ububntu
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"
